// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePhoto = "photos"

// Photo mapped from table <photos>
type Photo struct {
	ID          int64     `gorm:"column:id;not null" json:"id"`
	FilePath    string    `gorm:"column:file_path;not null" json:"file_path"`
	FileHash    string    `gorm:"column:file_hash;not null" json:"file_hash"`
	FileSize    int64     `gorm:"column:file_size" json:"file_size"`
	Width       int32     `gorm:"column:width" json:"width"`
	Height      int32     `gorm:"column:height" json:"height"`
	TakenAt     time.Time `gorm:"column:taken_at" json:"taken_at"`
	CameraMake  string    `gorm:"column:camera_make" json:"camera_make"`
	CameraModel string    `gorm:"column:camera_model" json:"camera_model"`
	LensModel   string    `gorm:"column:lens_model" json:"lens_model"`
	FocalLength float64   `gorm:"column:focal_length" json:"focal_length"`
	Aperture    float64   `gorm:"column:aperture" json:"aperture"`
	Iso         int32     `gorm:"column:iso" json:"iso"`
	Status      int32     `gorm:"column:status" json:"status"`
	CreatedAt   time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
}

// TableName Photo's table name
func (*Photo) TableName() string {
	return TableNamePhoto
}
