// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePhotoEmbedding = "photo_embeddings"

// PhotoEmbedding mapped from table <photo_embeddings>
type PhotoEmbedding struct {
	PhotoID   int64  `gorm:"column:photo_id;not null" json:"photo_id"`
	Embedding string `gorm:"column:embedding;not null" json:"embedding"`
}

// TableName PhotoEmbedding's table name
func (*PhotoEmbedding) TableName() string {
	return TableNamePhotoEmbedding
}
